# Generated by Django 5.2.8 on 2025-11-16 10:42

import django.db.models.deletion
import django.utils.timezone
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان/نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='عکس')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ارگان',
                'verbose_name_plural': 'ارگان ها',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تایمر')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تایمر',
                'verbose_name_plural': 'تایمر ها',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظر ها',
            },
        ),
    ]
