# Generated by Django 5.2.8 on 2025-11-16 11:42

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_org_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='عکس'),
        ),
    ]
