# Generated by Django 5.2.8 on 2025-11-16 11:45

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='کاور پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.UploadFile.upload_to, verbose_name='عکس کارت ملی'),
        ),
    ]
