# Generated by Django 5.2.8 on 2025-11-16 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='سوال')),
                ('answer1', models.CharField(max_length=100, verbose_name='پاسخ 1')),
                ('answer2', models.CharField(max_length=100, verbose_name='پاسخ 2')),
                ('correct_answer', models.CharField(choices=[('1', 'پاسخ 1'), ('2', 'پاسخ 2')], max_length=1, verbose_name='پاسخ صحیح')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ قابل پرداخت')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج سوال')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='GoldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=16, unique=True, verbose_name='سریال کارت')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فعالسازی')),
                ('expire_date', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gold_card', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_gold_card', to='lottery.questions', verbose_name='سوال')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_card_lottery_list', to='lottery.goldcard', verbose_name='کارت طلایی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lottery_list', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_lottery_list', to='lottery.questions', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'لیست قرعه کشی',
                'verbose_name_plural': 'لیست قرعه کشی',
            },
        ),
    ]
