# Generated by Django 5.2.8 on 2025-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldcard',
            options={'verbose_name': 'کارت طلایی', 'verbose_name_plural': 'کارت طلایی'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'answer1'), ('2', 'answer2')], max_length=1, verbose_name='پاسخ صحیح'),
        ),
    ]
